### ISSUE TITLE
electron edge case bug - Electron v28.2.0 on Node.js v20.11.0

### ISSUE THREAD

**Issue by Igloczek** [dotenvx/dotenvx#120] opened 2024-03-05 19:26 UTC
Hi, when importing the lib directly into ES module Node.js project, it doesn't work, because there is no `__dirname`. 

Faulty code:
https://github.com/dotenvx/dotenvx/blob/main/src/shared/packageJson.js#L4

Code on my end:
```js
import dotenvx from "@dotenvx/dotenvx"
dotenvx.config()
```
Error:
```
App threw an error during load
ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/[redacted]/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```

**Comment by motdotla** [comment] 2024-03-05 22:57
what node version and dotenvx version are you on, @Igloczek?

I can't reproduce this yet on `v21.6.1` and `dotenvx@0.24.0`

```js
// index.mjs
import dotenvx from "@dotenvx/dotenvx"
dotenvx.config()

console.log(`Hello ${process.env.HELLO}`)
```

```json
{
  "type": "module",
  "dependencies": {
    "@dotenvx/dotenvx": "^0.24.0"
  }
}
```

no errors for me

**Comment by motdotla** [comment] 2024-03-08 02:04
closing. let me know if still experiencing the issue and if so what versions you are on. thank you.

**Comment by motdotla** [comment] 2024-03-11 16:24
what electron version are you on? https://www.electronjs.org/docs/latest/tutorial/electron-timelines

from there I can probably get to a point of reproducing the issue.

**Comment by Igloczek** [comment] 2024-03-11 16:41
Electron v28.2.0 on Node.js v20.11.0

**Comment by motdotla** [comment] 2024-03-18 23:24
i haven't been able to duplicate this yet. @Igloczek are you able to set up a basic example and link to it as a github repo?

**Comment by motdotla** [comment] 2024-04-08 17:34
going to close. if anyone else runs into this, please let me know.

**Closed by motdotla** 2024-04-08 17:34 UTC
