### ISSUE TITLE
dotenvx encrypt does not create a public key - can't reproduce. need more info.

### ISSUE THREAD

**Issue by VictorioBerra** [dotenvx/dotenvx#417] opened 2024-10-22 14:28 UTC
Windows, dotenvx 1.20, created a .env.producton with HELLO=world, ran `dotenvx.exe encrypt -f .env.production` and NO public key header existed in the file. `dotenv.exe keypair -f .env.production` shows `{"DOTENV_PUBLIC_KEY_PRODUCTION"=null, DOTENV_PRIVATE_KEY_PRODUCTION: "redacted"}`

**Comment by motdotla** [comment] 2024-10-22 16:31
i can't reproduce on my non windows machine but I will try on windows later today.

in the meantime, can you check if your `env` currently happens to have a DOTENV_PUBLIC or DOTENV_PRIVATE key already set? i'm not sure how to do that on windows. on posix it is the `env` command.

**Comment by motdotla** [comment] 2024-10-22 16:32
also if you downgrade to `1.19.3` do you experience the same problem still? https://github.com/dotenvx/dotenvx/releases/tag/v1.19.3

(1.20.0 introduced new logic around handling preset global machine private/public keys)

**Comment by motdotla** [comment] 2024-10-25 22:09
i haven't been able to reproduce this @VictorioBerra. maybe it is a file encoding issue - though dotenvx does try to handle that https://github.com/dotenvx/dotenvx/blob/6248392d49bae432f8685b6f32546475e9196ef5/src/lib/services/run.js#L89

i'm going to close this until you can send more info or if others chime in experiencing the same.

**Closed by motdotla** 2024-10-25 22:09 UTC

**Comment by VictorioBerra** [comment] 2024-10-29 17:12
It definitely happened... but I cant repo anymore.

**Comment by motdotla** [comment] 2024-10-29 17:25
ok good to hear. let me know if it happens again. my best guess is an encoding edge case.
